---
language: python
services: docker

env:
  global:
    - ROLE_NAME: apache
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule ansible-lint docker yamllint

script:
  # Run tests.
  - molecule test --scenario-name default

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
