---

# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199 and
# https://github.com/geerlingguy/ansible-role-java/issues/64
- name: "Ensure 'man' directory exists."
  file:
    path: /usr/share/man/man1
    state: directory
    recurse: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'
    - graylog_install_java | bool

- debug:
    var: ansible_os_family

- name: "Set Command to check for Java Version (Debian)"
  set_fact:
    java_check_command: "/usr/sbin/update-java-alternatives --list | grep 1.{{ graylog_java_version }}  | tr -s ' ' | cut -f 3 -d ' '"
  when: ansible_os_family == 'Debian'

- name: "Set Command to check for Java Version (RedHat)"
  set_fact:
    java_check_command: "update-alternatives --display java | grep '^/' | awk '{print $1}' | grep 1.{{ graylog_java_version }} | head -1"
  when: ansible_os_family == 'RedHat'

- name: "Get target JDK binary path"
  shell:
    cmd: "{{ java_check_command }}" # noqa 305
  register: target_jdk_path
  changed_when: false

- name: "Assert JDK is found"
  assert:
    that: target_jdk_path is defined and target_jdk_path.rc == 0

- name: "Set Command to check for Java Version"
  set_fact:
    java_home: "{{ target_jdk_path.stdout |  regex_replace('^(.*)bin/java$', '\\1') }}"

- name: "Check that target JDK is installed"
  assert:
    that: java_home is defined
    fail_msg: "The target JAVA {{ graylog_java_version }} should be installed."

- name: "Assign the binary path to the target JDK"
  set_fact:
    graylog_java_binary: "{{ java_home }}/bin/java"

- name: "Assign the binary path to the target JDK"
  set_fact:
    graylog_java_binary: "{{ java_home }}/bin/java"
    graylog_java_home: "{{ java_home }}"

- name: "Make sure that we have the right java alternative Setup for the host {{ graylog_java_version }}"
  alternatives:
    name: java
    path: "{{ graylog_java_binary }}"
    link: /usr/bin/java
