---

- name: "Repositories should be updated"
  yum_repository:
    name: "mongodb-org"
    description: "MongoDB Repository"
    baseurl: "{{ graylog_mongodb_redhat_repo }}"
    gpgkey: "{{ graylog_mongodb_redhat_key }}"
    gpgcheck: "yes"
    enabled: "yes"

- name: "Package dependencies should be installed"
  yum:
    name: "{{ graylog_mongodb_package_dependencies | default([]) }}"
    state: present

- name: "MongoDB should be installed"
  yum:
    name: "mongodb-org"
    state: "present"

- name: "MongoDB service file should be installed"
  template:
    src: "mongodb.service-RedHat.j2"
    dest: "/lib/systemd/system/mongod.service"
    owner: "root"
    group: "root"
    mode: 0644
  when:
    - use_system_d|bool

- name: "Reload systemd configuration"
  systemd:
    daemon_reload: yes
  when:
    - use_system_d|bool
  changed_when: False

- name: "MongoDB should be configured"
  template:
    src: "mongodb.conf.j2"
    dest: "/etc/mongod.conf"
    owner: "root"
    group: "root"
    mode: 0644

- name: "Restart MongoDB"
  service:
    name: "mongod"
    state: "restarted"
    enabled: "yes"
  changed_when: False

- name: "SELinux port access should be granted for MongoDB"
  seport:
    ports: 27017
    proto: "tcp"
    setype: "mongod_port_t"
    state: "present"
  when: ansible_selinux is defined and ansible_selinux.status != 'disabled'

- name: "Wait for MongoDB to startup"
  wait_for:
    host: "127.0.0.1"
    port: 27017
    delay: 5
    connect_timeout: 1
