---

- block:
    - name: "APT Key should be accepted for the MongoDB repo (Ubuntu)"
      apt_key:
        url: "{{ graylog_mongodb_ubuntu_key }}"
        state: present

    - name: "Repositories should be updated (Ubuntu)"
      apt_repository:
        repo: "{{ graylog_mongodb_ubuntu_repo }}"
        state: "present"
        update_cache: True
  when:
    - ansible_distribution == 'Ubuntu'

- block:
    - name: "APT Key should be accepted for the MongoDB repo (Debian)"
      apt_key:
        url: "{{ graylog_mongodb_debian_key }}"
        state: present

    - name: "Repositories should be updated (Debian)"
      apt_repository:
        repo: "{{ graylog_mongodb_debian_repo }}"
        state: "present"
        update_cache: True
  when:
    - ansible_distribution == 'Debian'

- name: "MongoDB should be installed"
  apt:
    name: "mongodb-org"
    state: "present"
  changed_when: False

- name: "MongoDB service file should be installed"
  template:
    src: "mongodb.service-Debian.j2"
    dest: "/lib/systemd/system/mongod.service"
    owner: "root"
    group: "root"
    mode: 0644
  when:
    - ( use_system_d | bool )
    - ansible_distribution == 'Ubuntu'

- name: "Reload systemd configuration"
  systemd:
    daemon_reload: yes
  when:
    - use_system_d|bool
    - ansible_distribution == 'Ubuntu'
  changed_when: False

- name: "MongoDB should be configured"
  template:
    src: "mongodb.conf.j2"
    dest: "/etc/mongod.conf"
    owner: "root"
    group: "root"
    mode: 0644

- name: "Restart MongoDB"
  service:
    name: "mongod"
    state: "restarted"
    enabled: "yes"
  changed_when: False

- name: "Wait for MongoDB to startup"
  wait_for:
    host: "127.0.0.1"
    port: 27017
    delay: 5
    connect_timeout: 1
