---

- name: "Graylog server package should be installed"
  package:
    name: "graylog-server{% if graylog_server_version is defined %}={{ graylog_server_version }}{% endif %}"
    state: "{{ graylog_package_state }}"

- name: "Set elasticsearch priority to {{ graylog_es_debian_pin_version }} apt_preferences"
  template:
    src: "apt_preferences.d/debian_elasticsearch.j2"
    dest: "/etc/apt/preferences.d/elasticsearch"
    owner: "root"
    mode: 0644
  when: ansible_os_family == 'Debian'


- name: "Retrieve java related setups"
  include_tasks: "java.yml"

- name: "Directory should be created with correct ownership and privileges"
  file:
    path: "/etc/graylog/server"
    owner: "graylog"
    group: "graylog"
    mode: 0750

- name: "Graylog server should be configured"
  template:
    src: "graylog.server.conf.j2"
    dest: "/etc/graylog/server/server.conf"
    owner: "graylog"
    group: "graylog"
    mode: 0644

- name: "Graylog server defaults should be configured"
  template:
    src: "graylog.server.default.j2"
    dest: "{{ graylog_server_defaults_file_path }}"
    owner: "graylog"
    group: "graylog"
    mode: 0644

- name: "Graylog server should start after reboot"
  file:
    path: "/etc/init/graylog-server.override"
    state: "absent"

- name: "Restart graylog-server"
  service:
    name: "graylog-server"
    state: "restarted"
    enabled: "yes"
  changed_when: False

- name: "Wait for Graylog server to startup"
  uri:
    url: "{{ graylog_http_publish_uri }}"
    status_code: 200
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  when: graylog_not_testing
