---

- name: "Graylog repository package should be downloaded"
  get_url:
    url: "{{ graylog_generic_apt_deb_url }}"
    dest: "/tmp/graylog_repository.deb"
  when: graylog_manage_apt_repo

- name: "Package 'apt-transport-https' should be installed"
  apt:
    name: "apt-transport-https"
    state: present

- name: "Graylog repository package should be installed"
  apt:
    deb: "/tmp/graylog_repository.deb"
    state: present
    dpkg_options: "force-all"
  when: graylog_manage_apt_repo

- name: Update apt cache.
  apt: update_cache=true
